### ISSUE TITLE
undefined method `fetch' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by ThomasBush** [sgruhier/capistrano-db-tasks#63]
This is a recent development since I upgraded from ruby 2.2.0 to 2.2.2.  This occurs why I try to run any of the rails generators, specifically a migration is this instance.  

/Users/Thomas/.rvm/gems/ruby-2.2.2@HexGen/gems/capistrano-db-tasks-0.4/lib/capistrano-db-tasks/dbtasks.rb:5:in `<top (required)>': undefined method `fetch' for main:Object (NoMethodError)

Any idea what could cause such an error?  I have to comment the gem out of my gemfile to create migrations.

**Comment by Nimdis** [comment]
+1, caught the same error. it fires all the time, even when I start rails server. tried with ruby 4.1.2 and 4.2.1. any solutions?

**Comment by yfractal** [comment]
@ThomasBush  @Nimdis 
Please try `gem 'capistrano-db-tasks', '~> 0.4', :require => false`

**Comment by ThomasBush** [comment]
Perfect, this fixes everything for me!  Thanks!

**Comment by lanxichan** [comment]
And you need to add  this in deploy.rb
```Ruby
require 'capistrano-db-tasks'
```
